[package]
name = "nomic-rest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
nomic = { path = "..", features = ["full"] }
hex = "0.4.3"
tendermint-rpc = { version = "0.23.3", features = ["http-client"] }
tendermint = "0.23.5"
base64 = "0.13.0"
